title: "Gabriel Fernandes | Portfólio"
description: "Site pessoal e portfólio de Gabriel Fernandes, desenvolvedor Front-End, Suporte de TI, QA..."
theme: minima
author: "Gabriel Fernandes"
lang: pt-BR